<?php
$root=dirname(__DIR__); $main=file_get_contents($root.'/sabri-authentication.php'); $a=file_get_contents($root.'/includes/class-sa-activator.php'); $p=file_get_contents($root.'/includes/class-sauth-passkeys.php'); $adapter=file_get_contents($root.'/includes/class-sa-membership-adapter.php'); $baseline=file_get_contents($root.'/.github/workflows/baseline-integrity.yml'); $docs=file_get_contents($root.'/.github/workflows/canonical-storage-and-docs.yml'); $integration=file_get_contents($root.'/.github/workflows/file00-1.2.44-real-integration.yml'); $review=file_get_contents($root.'/.github/workflows/review-branch-integrity.yml'); $lock=file_get_contents($root.'/RELEASE-LOCK.json'); $readme=file_get_contents($root.'/readme.txt'); $report=file_get_contents($root.'/REVIEW-REPORT.md'); $fail=array();
$checks=array(
 array($main,"Version: 1.3.2",'plugin header release identity stale'), array($main,"SAUTH_VERSION', '1.3.2",'runtime release identity stale'), array($main,"SAUTH_DB_VERSION', '1.3.0",'DB migration identity stale'),
 array($p,"SCHEMA_VERSION        = '1.0.1'",'passkey migration identity stale'), array($p,'SHOW INDEX FROM','passkey readiness does not prove indexes'), array($p,"'credential_lookup_hash' => array( 0",'passkey lookup uniqueness is not a material postcondition'),
 array($a,'required_table_indexes','base storage does not define material index postconditions'), array($a,'table_indexes_ready','base storage does not verify indexes'), array($a,"'user_token'=>array(0",'session token uniqueness is not a material postcondition'), array($a,"'token_hash'=>array(0",'risk token uniqueness is not a material postcondition'),
 array($adapter,"MEMBERSHIP_APPLICATION_PATH = '/membership-application/'",'canonical membership application route is missing'), array($adapter,"MEMBERSHIP_SECURITY_PATH    = '/membership-security/'",'canonical membership security route is missing'), array($adapter,"MEMBERSHIP_STATUS_PATH      = '/membership-status/'",'canonical membership status route is missing'),
 array($baseline,"RELEASE_VERSION: '1.3.2'",'release CI version stale'), array($baseline,"DB_VERSION: '1.3.0'",'release CI DB version stale'), array($baseline,'tests/r31*-regression.php','release CI omits current corrective line'), array($baseline,'tests/r339-file00-canonical-route-contract-regression.php','release CI does not require R339 route-contract regression'),
 array($docs,"agent/file02-comprehensive-remediation-1.3.0",'documentation CI lost the preserved R337 branch-history marker'), array($docs,"'release_version':'1.3.2'",'documentation CI current release-lock truth stale'),
 array($integration,"FILE02_VERSION: '1.3.2'",'real integration version stale'), array($integration,'Prove exact File 00 managed-page source contract','real integration lacks exact File 00 managed-page source contract proof'), array($integration,'Prove File 02 resolves exact File 00 canonical membership routes','real integration lacks canonical membership-route resolution proof'), array($integration,'Rehearse legacy 1.2.1 passkey-column upgrade on real MariaDB','real integration lacks supported legacy passkey upgrade rehearsal'), array($integration,'Rehearse exact deployed stale passkey user_status index on real MariaDB','real integration lacks exact live stale-index rehearsal'), array($integration,'sauth_passkey_schema_version","1.0.0','legacy passkey schema input is not exercised'),
 array($review,'Temporary write-capable correction workflow remains','permanent review gate does not reject correction machinery'), array($lock,'"release_version": "1.3.2"','release lock version stale'), array($lock,'"database_version": "1.3.0"','release lock DB version stale'), array($lock,'"passkey_schema_version": "1.0.1"','release lock passkey schema stale'),
 array($readme,'Stable tag: 1.3.2','WordPress readme stable tag stale'), array($report,'Historical evidence notice','historical root review report can be mistaken for current evidence')
);
foreach($checks as $c){if(false===strpos($c[0],$c[1]))$fail[]=$c[2];}
foreach(array('sabri_profile','sabri_security_center','sabri_verification_status') as $forbidden){if(false!==strpos($adapter,$forbidden))$fail[]='invented membership route key remains: '.$forbidden;}
foreach(array('.github/workflows/r310-batch-correction.yml','.github/workflows/r310-v3-correction.yml','.github/workflows/r311-r320-correction.yml') as $f){if(file_exists($root.'/'.$f))$fail[]='temporary correction workflow remains: '.$f;}
if(is_dir($root.'/.github/forty-round-payload'))$fail[]='historical correction payload directory remains';
if($fail){fwrite(STDERR,"R320 regressions:\n- ".implode("\n- ",$fail)."\n");exit(1);} echo 'R320 final release regression PASS ('.(count($checks)+7)." assertions).\n";
