<?php
$root=dirname(__DIR__); $main=file_get_contents($root.'/sabri-authentication.php'); $a=file_get_contents($root.'/includes/class-sa-activator.php'); $p=file_get_contents($root.'/includes/class-sauth-passkeys.php'); $baseline=file_get_contents($root.'/.github/workflows/baseline-integrity.yml'); $docs=file_get_contents($root.'/.github/workflows/canonical-storage-and-docs.yml'); $integration=file_get_contents($root.'/.github/workflows/file00-1.2.43-real-integration.yml'); $review=file_get_contents($root.'/.github/workflows/review-branch-integrity.yml'); $lock=file_get_contents($root.'/RELEASE-LOCK.json'); $readme=file_get_contents($root.'/readme.txt'); $report=file_get_contents($root.'/REVIEW-REPORT.md'); $fail=array();
$checks=array(
 array($main,"Version: 1.2.4",'plugin header release identity stale'), array($main,"SAUTH_VERSION', '1.2.4",'runtime release identity stale'), array($main,"SAUTH_DB_VERSION', '1.2.1",'DB migration identity stale'),
 array($p,"SCHEMA_VERSION        = '1.0.1'",'passkey migration identity stale'), array($p,'SHOW INDEX FROM','passkey readiness does not prove indexes'), array($p,"'credential_lookup_hash' => array( 0",'passkey lookup uniqueness is not a material postcondition'),
 array($a,'required_table_indexes','base storage does not define material index postconditions'), array($a,'table_indexes_ready','base storage does not verify indexes'), array($a,"'user_token'=>array(0",'session token uniqueness is not a material postcondition'), array($a,"'token_hash'=>array(0",'risk token uniqueness is not a material postcondition'),
 array($baseline,"RELEASE_VERSION: '1.2.4'",'release CI version stale'), array($baseline,"DB_VERSION: '1.2.1'",'release CI DB version stale'), array($baseline,'tests/r31*-regression.php','release CI omits current corrective line'),
 array($docs,"fix/file02-account-taxonomy-parity-1.2.4",'documentation CI branch truth stale'), array($docs,"'1.2.4'",'documentation CI version truth stale'),
 array($integration,"FILE02_VERSION: '1.2.4'",'real integration version stale'), array($integration,'Rehearse legacy 1.2.1 passkey-column upgrade on real MariaDB','real integration lacks supported legacy passkey upgrade rehearsal'), array($integration,'sauth_passkey_schema_version","1.0.0','legacy passkey schema input is not exercised'),
 array($review,'Temporary write-capable correction workflow remains','permanent review gate does not reject correction machinery'), array($lock,'"release_version": "1.2.4"','release lock version stale'), array($lock,'"database_version": "1.2.1"','release lock DB version stale'), array($lock,'"passkey_schema_version": "1.0.1"','release lock passkey schema stale'),
 array($readme,'Stable tag: 1.2.4','WordPress readme stable tag stale'), array($report,'Historical evidence notice','historical root review report can be mistaken for current evidence')
);
foreach($checks as $c){if(false===strpos($c[0],$c[1]))$fail[]=$c[2];}
foreach(array('.github/workflows/r310-batch-correction.yml','.github/workflows/r310-v3-correction.yml','.github/workflows/r311-r320-correction.yml') as $f){if(file_exists($root.'/'.$f))$fail[]='temporary correction workflow remains: '.$f;}
if(is_dir($root.'/.github/forty-round-payload'))$fail[]='historical correction payload directory remains';
if($fail){fwrite(STDERR,"R320 regressions:\n- ".implode("\n- ",$fail)."\n");exit(1);} echo 'R320 final release regression PASS ('.(count($checks)+4)." assertions).\n";
