<?php
$root = dirname( __DIR__ );
$main = file_get_contents( $root . '/sabri-authentication.php' );
$registration = file_get_contents( $root . '/includes/class-sa-registration.php' );
$adapter = file_get_contents( $root . '/includes/class-sa-membership-adapter.php' );
$lock = json_decode( file_get_contents( $root . '/RELEASE-LOCK.json' ), true );
$readme = file_get_contents( $root . '/readme.txt' );
$status = file_get_contents( $root . '/STATUS.md' );
$baseline = file_get_contents( $root . '/.github/workflows/baseline-integrity.yml' );
$docs = file_get_contents( $root . '/.github/workflows/canonical-storage-and-docs.yml' );
$integration = file_get_contents( $root . '/.github/workflows/file00-1.2.44-real-integration.yml' );
$fail = array();
$req = static function ( $ok, $message ) use ( &$fail ) { if ( ! $ok ) { $fail[] = $message; } };
$req( false !== strpos( $main, 'Version: 1.3.4' ) && false !== strpos( $main, "SAUTH_VERSION', '1.3.4" ), 'runtime identity not 1.3.4' );
$req( false !== strpos( $main, "SAUTH_DB_VERSION', '1.3.0" ), 'DB identity not 1.3.0' );
$req( is_array( $lock ) && '1.3.4' === ( $lock['release_version'] ?? '' ), 'release lock not 1.3.4' );
$req( '1.3.0' === ( $lock['database_version'] ?? '' ) && '1.0.1' === ( $lock['passkey_schema_version'] ?? '' ), 'schema identities stale' );
$req( 'fix/file02-legacy-email-verification-reconciliation-1.3.4' === ( $lock['candidate_branch'] ?? '' ), 'candidate branch identity stale' );
$req( 'R341-email-verification-legacy-reconciliation' === ( $lock['review_line'] ?? '' ), 'current review line identity stale' );
$req( false === ( $lock['status']['staging_accepted'] ?? true ) && false === ( $lock['status']['live_deployed'] ?? true ) && false === ( $lock['status']['operational'] ?? true ), 'external completion falsely advanced' );
$req( false !== strpos( $readme, 'Stable tag: 1.3.4' ) && false !== strpos( $readme, '= 1.3.4 =' ) && false !== strpos( $readme, '= 1.3.3 =' ) && false !== strpos( $readme, '= 1.3.2 =' ) && false !== strpos( $readme, '= 1.3.1 =' ) && false !== strpos( $readme, '= 1.3.0 =' ) && false !== strpos( $readme, '= 1.2.3 =' ), 'WordPress readme identity/history invalid' );
$req( false !== strpos( $status, 'Version 1.3.0' ), 'status no longer preserves R337 base identity' );
$req( false !== strpos( $baseline, "RELEASE_VERSION: '1.3.4'" ), 'baseline workflow identity stale' );
$req( false !== strpos( $docs, "'release_version':'1.3.4'" ), 'docs workflow identity stale' );
$req( false !== strpos( $integration, "FILE02_VERSION: '1.3.4'" ) && false !== strpos( $integration, "FILE00_VERSION: '1.2.44'" ), 'real integration paired identity stale' );
$req( false !== strpos( $integration, '738aa2ab4b8be3d6cfdb3ecd46c88aa8d9ece3a0' ), 'real integration File00 exact pin stale' );
$req( false !== strpos( $integration, 'c4ab298b3ba2b870d507d32b36b1b4afd2771621' ), 'real integration File00 live-route baseline pin stale' );
$req( false !== strpos( $integration, 'Prove R341 legacy verified-email reconciliation against current File 00' ), 'real integration omits R341 reconciliation proof' );
$req( false !== strpos( $integration, 'Prove File 02 resolves exact File 00 canonical membership routes' ), 'real integration omits R339 canonical route proof' );
$req( false !== strpos( $integration, 'Rehearse exact deployed stale passkey user_status index on real MariaDB' ), 'real integration omits R338 live stale-index recovery' );
$req( false !== strpos( $registration, "'patient'" ) && false !== strpos( $registration, "'pharmacy'" ) && false !== strpos( $registration, "'clinic'" ) && false !== strpos( $registration, "'publisher'" ), 'canonical account choices incomplete' );
$req( false !== strpos( $adapter, "MEMBERSHIP_APPLICATION_KEY  = 'application'" ) && false !== strpos( $adapter, "MEMBERSHIP_SECURITY_KEY     = 'security'" ) && false !== strpos( $adapter, "MEMBERSHIP_STATUS_KEY       = 'status'" ), 'canonical File00 membership route keys incomplete' );
$req( false === strpos( $adapter, 'sabri_profile' ) && false === strpos( $adapter, 'sabri_security_center' ) && false === strpos( $adapter, 'sabri_verification_status' ), 'invented File00 membership route keys remain' );
$req( file_exists( $root . '/review-evidence/R332-REVIEW-FROZEN.md' ), 'R332 frozen review evidence missing' );
$req( file_exists( $root . '/tests/r339-file00-canonical-route-contract-regression.php' ), 'R339 route-contract regression missing' );
$req( file_exists( $root . '/tests/r340-passkey-assurance-cycle-regression.php' ), 'R340 passkey-assurance cycle regression missing' );
$req( file_exists( $root . '/tests/r341-email-verification-legacy-reconciliation-regression.php' ), 'R341 email reconciliation regression missing' );
$req( ! file_exists( $root . '/.github/workflows/tmp-account-taxonomy-parity-apply.yml' ), 'temporary taxonomy workflow remains' );
if ( $fail ) { fwrite( STDERR, "R332 current invariants:\n- " . implode( "\n- ", $fail ) . "\n" ); exit( 1 ); }
echo 'R332 release identity invariants PASS (25 assertions).' . PHP_EOL;
