<?php
$root = dirname( __DIR__ );
$passkeys = file_get_contents( $root . '/includes/class-sauth-passkeys.php' );
$main = file_get_contents( $root . '/sabri-authentication.php' );
$lock = json_decode( file_get_contents( $root . '/RELEASE-LOCK.json' ), true );
$lineage = json_decode( file_get_contents( $root . '/SOURCE-LINEAGE-LOCK.json' ), true );
$integration = file_get_contents( $root . '/.github/workflows/file00-1.2.44-real-integration.yml' );
$fail = array();
$req = static function ( $ok, $message ) use ( &$fail ) { if ( ! $ok ) { $fail[] = $message; } };
$req( false !== strpos( $passkeys, 'reconcile_legacy_credential_hash_index( $table )' ), 'legacy index reconciliation is not invoked before canonical column migration' );
$req( false !== strpos( $passkeys, "array( 'credential_hash' ) !== \$current['columns']" ), 'unexpected canonical-name index binding does not fail closed' );
$req( false !== strpos( $passkeys, 'credential_hash_legacy' ), 'legacy uniqueness preservation key is missing' );
$req( false !== strpos( $passkeys, 'DROP INDEX `credential_lookup_hash`, ADD UNIQUE KEY' ), 'stale canonical key name is not atomically replaced when legacy uniqueness needs preservation' );
$req( false !== strpos( $passkeys, '$canonical_name_free && $legacy_unique' ), 'postcondition does not verify freed canonical name and preserved legacy uniqueness' );
$req( false !== strpos( $main, 'Version: 1.3.0' ) && false !== strpos( $main, "SAUTH_VERSION', '1.3.0" ), 'recoverable runtime identity not 1.3.0' );
$req( false !== strpos( $main, "SAUTH_DB_VERSION', '1.3.0" ), 'recoverable DB identity is stale' );
$req( false !== strpos( $passkeys, "const SCHEMA_VERSION        = '1.0.1'" ), 'recoverable passkey schema identity changed unexpectedly' );
$req( false !== strpos( $main, "SAUTH_PASSKEY_CONTRACT_VERSION', '1.0.0" ), 'recoverable passkey assurance contract changed unexpectedly' );
$req( is_array( $lock ) && '1.3.0' === ( $lock['release_version'] ?? '' ), 'release lock recoverable runtime stale' );
$req( 'review/file02-r338-fresh-review-fix-2026-08-16' === ( $lock['candidate_branch'] ?? '' ), 'release lock branch stale' );
$integration_evidence = is_array( $lock['cross_file_integration_evidence'] ?? null ) ? $lock['cross_file_integration_evidence'] : array();
$prior_evidence = is_array( $lock['prior_cross_file_integration_evidence'] ?? null ) ? $lock['prior_cross_file_integration_evidence'] : array();
$req( ! empty( $lock['cross_file_blockers'] ) && 'pending_exact_head_review_source_only' === (string) ( $integration_evidence['status'] ?? '' ), 'current exact-head integration is falsely closed' );
$req( '1d7f215193d778b0977c8e50d738c42e1e5f66c2' === (string) ( $integration_evidence['file00_sha'] ?? '' ) && '1.2.44' === (string) ( $integration_evidence['file00_runtime'] ?? '' ), 'current File 00 integration target is stale' );
$req( 31850253635 === (int) ( $prior_evidence['workflow_run_id'] ?? 0 ), 'historical R335 integration evidence is missing' );
$req( 'f740ca65fc33031b98d7d75e5f27b7ccbeeefbf9' === (string) ( $prior_evidence['file02_sha'] ?? '' ), 'historical R335 File 02 SHA evidence is stale' );
$req( is_array( $lineage ) && false === ( $lineage['packaging_allowed'] ?? true ) && false === ( $lineage['current_source_has_complete_x24_scope'] ?? true ), 'R338 source-lineage containment is not fail-closed' );
$req( false === ( $lock['status']['staging_accepted'] ?? true ) && false === ( $lock['status']['live_deployed'] ?? true ) && false === ( $lock['status']['operational'] ?? true ), 'external completion falsely advanced' );
$req( false !== strpos( $integration, "FILE00_VERSION: '1.2.44'" ) && false !== strpos( $integration, "FILE02_VERSION: '1.3.0'" ), 'paired integration identities stale' );
$req( false !== strpos( $integration, '1d7f215193d778b0977c8e50d738c42e1e5f66c2' ), 'File 00 exact integration pin stale' );
$req( file_exists( $root . '/review-evidence/R335-REVIEW-FROZEN.md' ) && file_exists( $root . '/review-evidence/R335-ROOT-CAUSE-PROVEN.md' ), 'R335 frozen/root-cause evidence missing' );
$req( ! file_exists( $root . '/.github/workflows/r335-passkey-index-diagnostic.yml' ), 'temporary R335 diagnostic workflow remains' );
$req( ! file_exists( $root . '/tools/apply-r335-passkey-index-reconciliation.py' ), 'temporary R335 applicator remains' );
if ( $fail ) { fwrite( STDERR, "R335 regressions:\n- " . implode( "\n- ", $fail ) . "\n" ); exit( 1 ); }
echo 'R335 passkey index/source-lineage invariants PASS (23 assertions).' . PHP_EOL;
